name: Tests
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-go-tests:
    name: Unit Tests
    strategy:
      matrix:
        go-version: [ '1.18', '1.19', '1.20', '1.21', '1.22' ]
        os: [ 'ubuntu-latest', 'macos-latest', 'windows-latest' ]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Setup Go Environment
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
          check-latest: true
      - name: Prints Go version
        run: go version
      - name: Run Tests
        run: make test